version: "3.8" # docker-compose version

services: # services which our app going to use. (list of containers we want to create)
  backend-db: # container name
    image: mongo:latest # which image container will build on
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    networks: # adding network
      - backend-server
    volumes:
      - mongo-data:/data/db

  backend-server:
    build: . # build the Docker image for the service using the Dockerfile located in the current directory
    ports:
      - "4000:4000"
    networks: # adding network
      - backend-server
    depends_on:
      - backend-db

networks: # allow services to talk to each other while providing isolation from other docker container, running on the same host
  backend-server:
    driver: bridge

volumes: # enable persistence of database data across container restart
  mongo-data:
    driver: local
